version: "3.5"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lowracingdev
      - POSTGRES_PASSWORD=lowracing2025
      - POSTGRES_DB=lowracingdev
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
