version: "3.5"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=npg_mKH7w5Nbuoix
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
