app = "lowracing-api"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[deploy]
  release_command = "npx prisma migrate deploy"

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    timeout = "2s"
    restart_limit = 0