# Exported from Render on 2024-07-23T12:08:52Z
services:
- type: web
  name: thunder
  runtime: node
  repo: https://github.com/lowracing/thunder
  plan: free
  envVars:
  - key: JWT_SECRET
    sync: false
  - key: POSTGRES_DB
    sync: false
  - key: POSTGRES_PASSWORD
    sync: false
  - key: POSTGRES_USER
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: PORT
    sync: false
  region: virginia
  buildCommand: yarn
  startCommand: yarn start
version: "1"
